### ISSUE TITLE
CQARank, documentation

### ISSUE THREAD

**Issue by amaik** [yangliuy/TopicExpertiseModel#1]
Is there also code for the whole of CQArank, or is it just the topic expertise model? Also is there a readme or a small documentation that explains how to use the code? It is a bit hard to use without any explanation.
I want to use it as a baseline for my Master's thesis.

**Comment by yangliuy** [comment]
The implementation of CQARank can be found  in https://github.com/yangliuy/TopicExpertiseModel/tree/master/src/tem/linkas, which is TEPR.java . I didn't write much documents for this project code. I will try to add docs If I find a time slot later.
